# Generated by Django 4.1.5 on 2023-01-12 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_profile_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='slug',
            field=models.SlugField(default='', editable=False, max_length=200, unique=True),
        ),
    ]
