# Generated by Django 4.1.5 on 2023-01-10 13:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Name')),
            ],
        ),
        migrations.AlterField(
            model_name='post',
            name='status',
            field=models.ForeignKey(default='New', on_delete=django.db.models.deletion.PROTECT, related_name='status', to='blog.status', to_field='name', verbose_name='Status'),
        ),
    ]
